version: '3.8'

services:
  web:
    build: .
    image: bigagroparts_prod:web
    container_name: bigagroparts_prod.web
    tty: true
    stdin_open: true
    restart: always
    command: >
      bash -c "gunicorn parts_shop.wsgi:application --bind 0.0.0.0:8000 --workers=2 --threads=4 --worker-class=gthread"
    volumes:
      - .:/app
    ports:
      - 80:8000
    environment:
      PYTHONIOENCODING: UTF-8
      DJANGO_SETTINGS_MODULE: parts_shop.settings    
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    container_name: bigagroparts.db
    restart: always
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.postgres.env
    
volumes:
  postgres_data: