version: '3.3'

services:
  web_stag:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    image: bigagroparts_prod:web
    container_name: bigagroparts_prod.web
    tty: true
    stdin_open: true
    restart: always
    command: >
      sh -c "gunicorn parts_shop.wsgi:application --bind 0.0.0.0:8000 --workers=2 --threads=4 --worker-class=gthread --log-level=debug"
    volumes:
      - .:/app
    expose:
      - 8000
    environment:
      PYTHONIOENCODING: UTF-8
      DJANGO_SETTINGS_MODULE: parts_shop.settings    
    env_file:
      - ./.env.prod
    depends_on:
      - db_prod
  db_stag:
    image: postgres:14.0-alpine
    container_name: bigagroparts.db
    restart: always
    volumes: 
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.postgres.env
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web_prod
    
volumes:
  postgres_data_prod: