# Generated by Django 2.2 on 2021-11-04 15:19

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адреса')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Має починатися з +380', max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('wholesaler', models.BooleanField(blank=True, default=False, null=True, verbose_name='Статус оптовика')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='None/category.jpg', null=True, upload_to='uploads/category_images', verbose_name='Фото категорії')),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, max_length=200, null=True, populate_from='title', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Категорії',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Опис')),
                ('price', models.FloatField(max_length=200, verbose_name='Ціна')),
                ('availability', models.CharField(choices=[('1', 'Є в наявності'), ('0', 'Немає в наявносі'), ('2', 'Уточніть наявність')], default='1', max_length=20, verbose_name='Наявність')),
                ('wholesaler_price', models.FloatField(max_length=200, verbose_name='Оптова ціна')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення')),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, max_length=200, null=True, populate_from='title', unique=True)),
                ('categories', models.ManyToManyField(blank=True, to='core.Category')),
            ],
            options={
                'verbose_name_plural': 'Товари',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='None/subcategory.jpg', null=True, upload_to='uploads/sub_category_images', verbose_name='Фото підкатегорії')),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, max_length=200, null=True, populate_from='title', unique=True)),
                ('categories', models.ManyToManyField(to='core.Category')),
            ],
            options={
                'verbose_name_plural': 'Підкатегорії',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кількість')),
                ('ordered', models.BooleanField(default=False, verbose_name='Замовлення підтверджено')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name_plural': 'Товари в кошику',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформлення')),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False, verbose_name='Замовлення підтверджено')),
                ('order_total_price', models.FloatField(blank=True, default=0.0, max_length=200, verbose_name='Вартість замовлення')),
                ('order_status', models.CharField(choices=[('OA', 'Замовлення прийнято'), ('OIP', 'Замовлення виконується'), ('OF', 'Замовлення виконано')], default='OA', max_length=20, verbose_name='Статус замовлення')),
                ('items', models.ManyToManyField(to='core.OrderItem', verbose_name='Товари')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='None/item.jpg', null=True, upload_to='uploads/', verbose_name='Фото деталі')),
                ('default', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
            options={
                'verbose_name_plural': 'Фото товарів',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='core.SubCategory'),
        ),
    ]
