# Generated by Django 2.2 on 2022-01-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211216_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_price',
            field=models.FloatField(blank=True, default=0.0, max_length=200, verbose_name='Вартість товару'),
        ),
    ]
