# Generated by Django 2.2 on 2022-01-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220127_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.CharField(choices=[('1', 'Є в наявності'), ('0', 'Немає в наявності'), ('2', 'Уточніть наявність')], default='1', max_length=20, verbose_name='Наявність'),
        ),
    ]
