# Generated by Django 2.2 on 2022-01-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220126_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('id',), 'verbose_name_plural': 'Товари в кошику'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.IntegerField(default=0, verbose_name='ID кошика'),
        ),
    ]
