# Generated by Django 2.2 on 2022-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220131_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата замовлення'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата формування'),
        ),
    ]
