# Generated by Django 2.2 on 2022-01-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220127_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Ім'я по батькові"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name="Ім'я"),
        ),
    ]
