# Generated by Django 2.2 on 2022-01-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220127_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_status',
            field=models.CharField(choices=[('LC', 'Залишений кошик'), ('OA', 'Замовлення прийнято'), ('OIP', 'Замовлення виконується'), ('OF', 'Замовлення виконано')], default='LC', max_length=20, verbose_name='Статус замовлення'),
        ),
    ]
