# Generated by Django 2.2 on 2022-01-26 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20220126_2009'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.CharField(max_length=100, verbose_name='Сума замовлення')),
                ('delivery_method', models.CharField(choices=[('NP', 'Нова Пошта'), ('KU', "Кур'єр (по м. Луцьк)")], default='NP', max_length=5, verbose_name='Метод доставки:')),
                ('nova_poshta', models.CharField(blank=True, help_text="Введіть лише число без '№'", max_length=5, verbose_name='№ відділення Нової Пошти')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто / село')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адреса для доставки по Луцьку')),
                ('landmark', models.CharField(blank=True, max_length=100, verbose_name='Область')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Контактний номер телефону')),
                ('email', models.EmailField(max_length=200, verbose_name='Адреса електронної пошти')),
                ('payment_method', models.CharField(choices=[('PAD', 'Оплата при отриманні'), ('PBD', 'Оплата за реквізитами (передоплата)')], default='PBD', max_length=10, verbose_name='Метод оплати')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cart', verbose_name='Кошик')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Замовлення',
            },
        ),
    ]
