# Generated by Django 2.2 on 2022-01-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='r', max_length=200, verbose_name='ПІБ покупця'),
            preserve_default=False,
        ),
    ]
